spring:
  profiles:
    active: dev

#mybatis config begin
mybatis:
  mapper_locations: classpath:mapper/*.xml
#mybatis config end

#wx config begin
wx:
  app:
    appid: wx843fbc69f150bc81
    secret: 71f99218047be78e56e52e4ed9d3512c
#wx config end

---
#DataSource config begin
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb?autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      maximumPoolSize: 20

#DataSource config end

#file config begin
file:
  location: /Users/romanluo/workspace/jinxin/target/file
#file config end

---
#DataSource config begin
spring:
  profiles: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.132.84.118:3306/jfzpay?autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8mb4
    username: jfzpayer
    password: 5giUgaUzcf5M5v
    hikari:
          maximumPoolSize: 100

#DataSource config end

#file config begin
file:
  location: /data/jfzpay/jinxin/apache-tomcat-8.5.6/file
#file config end

